import { StrictMode, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Status = "CURRENT" | "STALE" | "UNKNOWN" | "UNAVAILABLE" | "CONFLICTING";
type Settings = {
  version: number; appearance: "system" | "light" | "night"; accent: "ember" | "sage" | "sky";
  density: "comfortable" | "compact"; reduced_motion: boolean; text_scale: "small" | "normal" | "large";
  display_mode: "wall" | "tablet" | "phone" | "desktop"; visible_widgets: string[]; widget_order: string[];
};
type Bootstrap = { identity: { display_name: string; assurance: string }; household: { name: string }; theme: Pick<Settings, "appearance" | "accent" | "density" | "reduced_motion" | "text_scale">; layout: Pick<Settings, "display_mode" | "visible_widgets" | "widget_order">; csrf_token: string };
type Task = { task_id: string; title: string; status: string; next_run_at?: string };
type CalendarEvent = { event_id: string; title: string; start_at: string; end_at: string; status: string; version?: number };
type Home = { household: { name: string; status: Status; summary: string }; security: { status: Status; label: string }; presence: { people: { name: string; state: string }[] }; weather: { status: Status; summary: string }; calendar: CalendarEvent[]; tasks: Task[]; controls: { control_id: string; label: string; state: string; capability?: string }[]; activity: { summary: string; status: Status }[]; voice: { status: Status; label: string } };
type Capability = { id: string; label: string; state: string; detail?: string };

const api = async <T,>(path: string, options?: RequestInit): Promise<T> => {
  const response = await fetch(path, { ...options, credentials: "same-origin", headers: { Accept: "application/json", ...(options?.headers ?? {}) } });
  if (!response.ok) { const body = (await response.json().catch(() => ({}))) as { detail?: string }; throw new Error(body.detail ?? "ANIMA could not complete that request"); }
  return response.json() as Promise<T>;
};

function StatusPill({ status }: { status: Status | string }) { return <span className={`status status-${status.toLowerCase().replaceAll("/", "-")}`}>{status.replaceAll("_", " ")}</span>; }
function Card({ title, children, className = "" }: { title: string; children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}><div className="card-heading"><h2>{title}</h2></div>{children}</section>; }
function useMutation(csrf: string, refresh: () => Promise<void>, setError: (value: string) => void) {
  return async (path: string, payload: Record<string, unknown> = {}) => { try { setError(""); await api(path, { method: "POST", body: JSON.stringify({ payload }), headers: { "Content-Type": "application/json", "X-Anima-CSRF": csrf, Origin: window.location.origin } }); await refresh(); } catch (err) { setError(err instanceof Error ? err.message : "ANIMA could not complete that request"); } };
}

function App() {
  const [bootstrap, setBootstrap] = useState<Bootstrap | null>(null); const [home, setHome] = useState<Home | null>(null); const [settings, setSettings] = useState<Settings | null>(null); const [capabilities, setCapabilities] = useState<Capability[]>([]); const [tab, setTab] = useState("Home"); const [message, setMessage] = useState(""); const [reply, setReply] = useState(""); const [error, setError] = useState("");
  const refresh = async () => { try { setError(""); const [b, h, c, s] = await Promise.all([api<Bootstrap>("/api/v1/bootstrap"), api<Home>("/api/v1/home"), api<{ items: Capability[] }>("/api/v1/capabilities"), api<{ settings: Settings }>("/api/v1/settings")]); setBootstrap(b); setHome(h); setCapabilities(c.items); setSettings(s.settings); } catch (err) { setError(err instanceof Error ? err.message : "Anima is unavailable"); } };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (!bootstrap) return; const events = new EventSource("/api/v1/events"); const invalidate = () => void refresh(); ["home.invalidated", "tasks.changed", "calendar.changed", "activity.changed", "conversation.completed", "capabilities.changed", "refresh.required"].forEach((name) => events.addEventListener(name, invalidate)); return () => events.close(); }, [bootstrap]);
  useEffect(() => { if (!settings) return; const root = document.documentElement; root.dataset.appearance = settings.appearance; root.dataset.accent = settings.accent; root.dataset.density = settings.density; root.dataset.textScale = settings.text_scale; root.dataset.reducedMotion = settings.reduced_motion ? "true" : "false"; }, [settings]);
  const send = async () => { if (!message.trim() || !bootstrap) return; try { setError(""); const result = await api<{ response: string }>("/api/v1/conversation", { method: "POST", body: JSON.stringify({ text: message.trim() }), headers: { "Content-Type": "application/json", "X-Anima-CSRF": bootstrap.csrf_token, Origin: window.location.origin } }); setReply(result.response); setMessage(""); } catch (err) { setError(err instanceof Error ? err.message : "Anima could not respond"); } };
  const mutate = useMutation(bootstrap?.csrf_token ?? "", refresh, setError); const greeting = useMemo(() => bootstrap ? `Good evening, ${bootstrap.identity.display_name}.` : "Connecting to Anima…", [bootstrap]);
  if (!bootstrap || !home || !settings) return <main className="shell centered"><div className="brand-mark">A</div><h1>Anima</h1><p>{error || "Connecting to your home…"}</p>{error && <button onClick={() => void refresh()}>Try again</button>}</main>;
  const degraded = capabilities.some((item) => item.state === "degraded"); const nav = ["Home", "Anima", "Tasks & Calendar", "Activity", "Capabilities", "Settings"];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div><strong>Anima</strong><small>home intelligence</small></div></div><nav aria-label="Primary navigation">{nav.map((item) => <button key={item} className={tab === item ? "nav-item active" : "nav-item"} onClick={() => setTab(item)}>{item}</button>)}</nav><div className="sidebar-footer"><StatusPill status={degraded ? "degraded" : "online"} /><span>{degraded ? "Some capabilities degraded" : "Core online"}</span></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">{bootstrap.household.name}</p><h1>{tab === "Home" ? greeting : tab}</h1></div><button className="avatar" aria-label="Current household member">H</button></header>{error && <div className="notice error" role="alert">{error}</div>}{tab === "Home" && <HomeView home={home} mutate={mutate} reply={reply} />}{tab === "Anima" && <Card title="Talk with Anima" className="conversation"><p className="muted">Ask about your home, plan a reminder, or request help. Responses stay within the local ANIMA boundary.</p><Composer message={message} setMessage={setMessage} send={send} />{reply && <div className="reply" aria-live="polite"><strong>Anima</strong><p>{reply}</p></div>}</Card>}{tab === "Tasks & Calendar" && <TaskCalendar tasks={home.tasks} calendar={home.calendar} mutate={mutate} />}{tab === "Activity" && <Card title="Recent activity"><ul className="clean-list">{home.activity.map((item, index) => <li key={`${item.summary}-${index}`}><span>{item.summary}</span><StatusPill status={item.status} /></li>)}</ul></Card>}{tab === "Capabilities" && <Capabilities items={capabilities} />}{tab === "Settings" && <SettingsPanel value={settings} csrf={bootstrap.csrf_token} onSaved={setSettings} setError={setError} />}</main></div>;
}

function HomeView({ home, mutate, reply }: { home: Home; mutate: (path: string, payload?: Record<string, unknown>) => Promise<void>; reply: string }) { return <div className="dashboard"><Card title="At a glance" className="hero"><p className="hero-copy">{home.household.summary}</p><div className="metric-row"><div><span>Presence</span><strong>{home.presence.people[0]?.state ?? "unknown"}</strong></div><div><span>Security</span><strong><StatusPill status={home.security.status} /></strong></div><div><span>Weather</span><strong><StatusPill status={home.weather.status} /></strong></div></div></Card><Card title="People at home"><ul className="clean-list">{home.presence.people.map((person) => <li key={person.name}><span><span className="person-dot" />{person.name}</span><StatusPill status={person.state} /></li>)}</ul></Card><Card title="Weather"><p className="muted">{home.weather.summary}</p></Card><Card title="Coming up"><ul className="clean-list">{home.calendar.map((event) => <li key={event.event_id}><span>{event.title}</span><time>{new Date(event.start_at).toLocaleString([], { weekday: "short", hour: "numeric", minute: "2-digit" })}</time></li>)}</ul></Card><Card title="Things to do"><ul className="clean-list">{home.tasks.map((task) => <li key={task.task_id}><span>{task.title}</span><StatusPill status={task.status} /></li>)}</ul></Card><Card title="Home controls"><ul className="clean-list">{home.controls.length ? home.controls.map((control) => <li key={control.control_id}><span>{control.label}<small className="muted control-state">{control.state}</small></span><span className="button-row"><button onClick={() => void mutate(`/api/v1/controls/${control.control_id}`, { state: true })}>On</button><button onClick={() => void mutate(`/api/v1/controls/${control.control_id}`, { state: false })}>Off</button></span></li>) : <li className="muted">No commissioned controls are available.</li>}</ul></Card><Card title="Anima"><p className="muted">{reply || "I’m here when you need a hand."}</p></Card><Card title="Voice"><p className="muted">{home.voice.label}</p></Card></div>; }
function Composer({ message, setMessage, send }: { message: string; setMessage: (value: string) => void; send: () => Promise<void> }) { return <div className="composer"><label htmlFor="message">Message Anima</label><textarea id="message" value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder="What would you like to know?" /><button onClick={() => void send()}>Send</button></div>; }
function TaskCalendar({ tasks, calendar, mutate }: { tasks: Task[]; calendar: CalendarEvent[]; mutate: (path: string, payload?: Record<string, unknown>) => Promise<void> }) { const [title, setTitle] = useState(""); const [when, setWhen] = useState(""); const [note, setNote] = useState(""); const [eventTitle, setEventTitle] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); return <div className="dashboard"><Card title="Tasks"><form className="stack" onSubmit={(event) => { event.preventDefault(); void mutate("/api/v1/tasks", { title, when, note }).then(() => { setTitle(""); setWhen(""); setNote(""); }); }}><label>Reminder title<input required value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>When<input required type="datetime-local" value={when} onChange={(event) => setWhen(event.target.value)} /></label><label>Note<input value={note} onChange={(event) => setNote(event.target.value)} /></label><button type="submit">Create task</button></form><ul className="clean-list list-spaced">{tasks.map((task) => <li key={task.task_id}><span>{task.title}<small className="muted">{task.next_run_at ? new Date(task.next_run_at).toLocaleString() : ""}</small></span><span className="button-row"><StatusPill status={task.status} /><button onClick={() => void mutate(`/api/v1/tasks/${task.task_id}/pause`)}>Pause</button><button onClick={() => void mutate(`/api/v1/tasks/${task.task_id}/resume`)}>Resume</button><button onClick={() => void mutate(`/api/v1/tasks/${task.task_id}/cancel`)}>Cancel</button></span></li>)}</ul></Card><Card title="Calendar"><form className="stack" onSubmit={(event) => { event.preventDefault(); void mutate("/api/v1/calendar", { title: eventTitle, start_at: new Date(start).toISOString(), end_at: new Date(end).toISOString(), timezone: "UTC" }).then(() => { setEventTitle(""); setStart(""); setEnd(""); }); }}><label>Event title<input required value={eventTitle} onChange={(event) => setEventTitle(event.target.value)} /></label><label>Starts<input required type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Ends<input required type="datetime-local" value={end} onChange={(event) => setEnd(event.target.value)} /></label><button type="submit">Create event</button></form><ul className="clean-list list-spaced">{calendar.map((event) => <li key={event.event_id}><span>{event.title}<small className="muted">{new Date(event.start_at).toLocaleString()}</small></span><span className="button-row"><StatusPill status={event.status} /><button onClick={() => void mutate(`/api/v1/calendar/${event.event_id}/update`, { expected_version: event.version ?? 1, title: event.title })}>Update</button><button onClick={() => void mutate(`/api/v1/calendar/${event.event_id}/cancel`, { expected_version: event.version ?? 1 })}>Cancel</button></span></li>)}</ul></Card></div>; }
function SettingsPanel({ value, csrf, onSaved, setError }: { value: Settings; csrf: string; onSaved: (value: Settings) => void; setError: (value: string) => void }) { const [draft, setDraft] = useState(value); useEffect(() => setDraft(value), [value]); const save = async () => { try { const result = await api<{ settings: Settings }>("/api/v1/settings", { method: "PUT", body: JSON.stringify({ payload: draft }), headers: { "Content-Type": "application/json", "X-Anima-CSRF": csrf, Origin: window.location.origin } }); onSaved(result.settings); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Settings could not be saved"); } }; return <Card title="Household interface"><p className="muted">Presentation-only preferences are bounded by Core and never change identity, policy, or device authority.</p><div className="settings-form"><label>Appearance<select value={draft.appearance} onChange={(event) => setDraft({ ...draft, appearance: event.target.value as Settings["appearance"] })}><option value="system">System</option><option value="light">Light</option><option value="night">Night</option></select></label><label>Accent<select value={draft.accent} onChange={(event) => setDraft({ ...draft, accent: event.target.value as Settings["accent"] })}><option value="ember">Ember</option><option value="sage">Sage</option><option value="sky">Sky</option></select></label><label>Density<select value={draft.density} onChange={(event) => setDraft({ ...draft, density: event.target.value as Settings["density"] })}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label>Text scale<select value={draft.text_scale} onChange={(event) => setDraft({ ...draft, text_scale: event.target.value as Settings["text_scale"] })}><option value="small">Small</option><option value="normal">Normal</option><option value="large">Large</option></select></label><label className="checkbox"><input type="checkbox" checked={draft.reduced_motion} onChange={(event) => setDraft({ ...draft, reduced_motion: event.target.checked })} /> Reduce motion</label></div><button onClick={() => void save()}>Save preferences</button></Card>; }
function Capabilities({ items }: { items: Capability[] }) { return <Card title="Capabilities"><ul className="clean-list">{items.map((item) => <li key={item.id}><span>{item.label}{item.detail && <small className="muted">{item.detail}</small>}</span><StatusPill status={item.state} /></li>)}</ul></Card>; }

createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
